title: "Albert Roger"
author: "Albert Roger"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true        # show site description
show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://albert-roger.github.io/", title: "Home"}
  - {file: "research.md", title: "Research"}
  - {url: "https://www.dropbox.com/scl/fi/6yiors0uy7zxbbwpld99l/rogercv.pdf?rlkey=8urpzzww0tr678hvtk4mizpq5&st=otqx67o2&dl=0", title: "CV"}
  #- {file: "projects.md", title: "Projects" }



external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:albert.roger.figuerola@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/albert-roger"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Albert_RogerF"}
  - {title: Mastodon, icon: mastodon, url: "https://econtwitter.net/@Albert_RogerF"}
  #- {title: BlueSky, icon: bluesky, url: "https://bsky.app/profile/albertroger.bsky.social"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/albert-roger-3a802118/"}
  - {title: Max Planck Institute for Innovation and Competition, url: "https://www.ip.mpg.de/en/persons/roger-albert.html"}
  - {title: ZEW Mannheim}
  - {title: Heidelberg University}
  - {title: TU Munich}




comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
